import { createFileRoute } from "@tanstack/react-router";
import { AnimatePresence, motion } from "motion/react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { DoodleCat,DoodleCoffee,DoodleFlower,DoodleHeadphones,DoodleHeart,DoodleMoon,DoodleStar } from "@/components/scrapbook/Doodles";
export const Route=createFileRoute("/little-things")({head:()=>({meta:[{title:"Tiny things — For You"},{name:"description",content:"A notebook page of tiny, low-pressure things that might make today one percent better."},{property:"og:title",content:"Tiny things that might help"},{property:"og:description",content:"No grand advice. Just water, a nap, something dumb to watch, or a text."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:LittleThings});
const notes=[['Drink some water','Your brain is mostly soup. Hydrate the soup.'],['Eat something pls.','Even a snack counts. No ceremony required.'],['Go outside for 5 minutes.','The sky might be doing something nice.'],['Listen to something you like.','One song. Loud enough to interrupt the thoughts.'],['Take a stupidly long nap.','Rest is not something you have to earn.'],['Text me.','Yep. I mean it.'],['Watch something dumb.','The dumber, the better.'],['Do absolutely nothing for a while.','This is officially allowed.']];
const happy=["You’re doing better than you think.","Breathe. One thing at a time.","This day is allowed to suck.","Tomorrow can be different.","You’re not alone."];
function LittleThings(){const [selected,setSelected]=useState<number|null>(null);const [message,setMessage]=useState('');const [burst,setBurst]=useState(0);return <main className="scrap-page things-page"><header className="things-heading"><span>page 03 / no pressure</span><h1>Tiny things that might make your day <mark>1% better</mark></h1><p>Pick one. Or ignore all of them. Also valid.</p></header><div className="things-board">{notes.map(([title,reply],i)=><motion.button type="button" key={title} className={`sticky-note note-${i+1} ${selected===i?'picked':''}`} onClick={()=>setSelected(i)} whileTap={{scale:.96,rotate:i%2?2:-2}} aria-expanded={selected===i}><b>{title}</b><AnimatePresence>{selected===i&&<motion.span initial={{opacity:0,height:0}} animate={{opacity:1,height:'auto'}} exit={{opacity:0,height:0}}>{reply}</motion.span>}</AnimatePresence></motion.button>)}<DoodleFlower className="board-flower"/><DoodleCoffee className="board-coffee"/><DoodleHeadphones className="board-headphones"/><DoodleMoon className="board-moon"/><DoodleCat className="board-cat"/></div><section className="emergency"><p>for emergency use only*</p><h2>Emergency happiness button</h2><div className="burst-zone"><Button variant="doodleRed" size="lg" onClick={()=>{const next=happy[Math.floor(Math.random()*happy.length)] ?? happy[0];setMessage(next ?? "You’re not alone.");setBurst(v=>v+1)}}>PRESS WHEN EVERYTHING SUCKS</Button><AnimatePresence>{message&&<motion.div key={burst} className="comfort-result" initial={{scale:.8,opacity:0,rotate:-2}} animate={{scale:1,opacity:1,rotate:1}}><DoodleStar/><DoodleHeart/><strong>{message}</strong><DoodleStar/></motion.div>}</AnimatePresence></div><small>*not medically reviewed. personally approved.</small></section></main>}
